### ISSUE TITLE
Variable explorer keeps showing all CDM variables after you select a network

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1487]
**What version of EMX2 are you using (see footer)**
8.110.0

**Describe the bug**
When you select a network in the variable explorer OR after you go to the variables of a certain network, all CDM variables of all networks are still shown.

**To Reproduce**
1. [Go to 'https://emx2.test.molgenis.org'](https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/variable-explorer)
2. Select a network
3. Variables should be filtered, but that doesn't happen.

1. Go to a specific network https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EPHOR/variables2. 
2. Only variables of this network should be visible.3. 

**Expected behavior**
Selection of network filters CDM variables

**Comment by connoratrug** [comment]
@marijevdgeest fixen in 8.121.0 ?

**Comment by connoratrug** [comment]
fixed / can not reproduce in 8.121.1

**Comment by marijevdgeest** [comment]
I still have this issue in the data-catalogue v8.121.2: https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/EXPANSE/variables

**Comment by marijevdgeest** [comment]
Variable Explorer should only show EXPANSE_CDM variables, but shows all CDM variables 
<img width="1454" alt="Screenshot 2022-10-04 at 14 44 34" src="https://user-images.githubusercontent.com/8653334/193822623-df0ab038-1d7b-4fa2-9116-4070a9266490.png">

**Comment by mswertz** [comment]
cannot reproduce in current installment [v8.209.1](https://github.com/molgenis/molgenis-emx2/releases/tag/vv8.209.1).
