### ISSUE TITLE
Link to download reports is missing schema name

### ISSUE THREAD

**Issue by hslh** [molgenis/molgenis-emx2#5501]
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

Software version: v13.48.1. Database version: 29. 

### Description

The reports page contains links to download the output of the report as zip/json/excel. These links are missing the schema name, so they do not work. 

### Reproduction steps

1. Go to 'https://directory.bbmri-eric.eu/ERIC/reports#/0' or any other report
2. Click on 'download as excel'
3. See error: `File not found: /api/reports/excel`
4. Correct link is https://directory.bbmri-eric.eu/ERIC/api/reports/excel?id=Collections

### Expected behaviour

I expect the link to point to the right download URL

**Comment by willemijn-oudijk** [comment]
I believe this issue is fixed in version v13.71.1. (Not specifically because of this version, but I noticed it in this version.)

**Comment by hslh** [comment]
I still get it at https://molgeniscatalogue.org/catalogue/reports#/0 , which is on v13.72.5

**Comment by hslh** [comment]
It works on https://emx2.dev.molgenis.org/, but not on https://hessel1.molgenis.net/, both on the same emx2 version, indicating that it is server-specific, perhaps something to do with the nginx config?
